#!/bin/sh
set -e

# If the package is removed, purged or installation is aborted, try to
# remove the default mountpoints.
#
# Failure to do so is not considered fatal, because they may be in use by
# the system administrator or some other daemon on the system.
if [ "$1" = remove -o "$1" = abort-install -o "$1" = purge ]; then
    rm -f /media/usb 2> /dev/null || :
    for i in 0 1 2 3 4 5 6 7; do
	rmdir /media/usb$i 2> /dev/null || :
    done
fi

# Automatically added by dh_installdeb/12.1.1
dpkg-maintscript-helper rm_conffile /etc/udev/rules.d/z60_usbmount.rules 0.0.12 -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/12.1.1
dpkg-maintscript-helper rm_conffile /etc/udev/usbmount.rules 0.0.20 -- "$@"
# End automatically added section


exit 0
