#!/bin/sh
set -e

# If the package is installed, try to create the default mountpoints.
# Failure to do so is not considered fatal.
if [ "$1" = install ]; then
    mkdir /media 2> /dev/null || :
    for i in 0 1 2 3 4 5 6 7; do
	mkdir /media/usb$i 2> /dev/null || :
    done
    ln -s usb0 /media/usb 2> /dev/null || :
fi

# Automatically added by dh_installdeb/12.1.1
dpkg-maintscript-helper rm_conffile /etc/udev/usbmount.rules 0.0.20 -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/12.1.1
dpkg-maintscript-helper rm_conffile /etc/udev/rules.d/z60_usbmount.rules 0.0.12 -- "$@"
# End automatically added section


exit 0
