#!/bin/sh
set -e

# Remove contents of /var/run/usbmount before the package is removed.
if [ "$1" = remove ]; then
    rm -f /var/run/usbmount/*
fi

# Automatically added by dh_installdeb/12.1.1
dpkg-maintscript-helper rm_conffile /etc/udev/rules.d/z60_usbmount.rules 0.0.12 -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/12.1.1
dpkg-maintscript-helper rm_conffile /etc/udev/usbmount.rules 0.0.20 -- "$@"
# End automatically added section


exit 0
